name: CI/CD Pipeline to DockerHub

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: kunalkumarthalautiya/autodeploy-lite
  TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:$TAG .

    - name: Tag with Git SHA
      run: docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:${{ github.sha }}

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push latest tag
      run: docker push $IMAGE_NAME:$TAG

    - name: Push SHA tag
      run: docker push $IMAGE_NAME:${{ github.sha }}
