name: CI/CD Pipeline to EC2

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: kunalkumarthalautiya/autodeploy-lite
  TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:$TAG .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push to DockerHub
      run: docker push $IMAGE_NAME:$TAG

    - name: SSH into EC2 & Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          bash ~/autodeploy-lite/deploy/ec2-deploy.sh $IMAGE_NAME $TAG

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,job,ref
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
